import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppProviders from "@/components/providers/AppProviders";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import ResponsiveWrapper from "./ResponsiveWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark:selection:bg-cyan-100 dark:selection:text-cyan-800 selection:bg-cyan-200 selection:text-cyan-900"
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <AppProviders>
          <ResponsiveWrapper>
            {children}
          </ResponsiveWrapper>
        </AppProviders>
        <Toaster richColors />
      </body>
    </html>
  );
}